# Generated by Django 4.2.1 on 2023-06-05 07:30

import datetime
from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpostpage_body_alter_blogpostpage_post_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 14, 30, 8, 705869)),
        ),
        migrations.AlterField(
            model_name='blogsinglepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='blogsinglepage',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 14, 30, 8, 705869)),
        ),
    ]
